/*
 * Copyright (c) 2021 Mark Crowe <https://github.com/markcrowe-com>. All rights reserved.
 */
package com.markcrowe.proportionalrepresentationvoting.windows;

import com.markcrowe.proportionalrepresentationvoting.Constituency;
import com.markcrowe.proportionalrepresentationvoting.Election;

public class ElectionInternalFrame extends javax.swing.JInternalFrame
{
	public ElectionInternalFrame(Constituency[] constituencies)
	{
		initComponents();
		election.setConstituencies(constituencies);
		initializeConstituencyComboBox();
	}
	//
	//	methods
	//
	public void loadResults()
	{
		election.runElection();
		election.calculatePartyResults();
		showResults(0);
		showPartyResults();
	}
	public void showPartyResults()
	{
		partyResultsTextArea.setText(election.getPartyResults());
	}
	public void showResults(int id)
	{
		constituencyResultsTextArea.setText(election.getConstituencies()[id].toString());
	}
	private void constituencyComboBoxActionPerformed()
	{
		showResults(constituencyComboBox.getSelectedIndex());
	}
	private void initializeConstituencyComboBox()
	{
		for(Constituency constituency : election.getConstituencies())
			constituencyComboBox.addItem(constituency.getName());
	}
	//
	//	fields
	//
	private final Election election = new Election();

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        constituencyComboBox = new javax.swing.JComboBox<>();
        partyResultsTextArea = new javax.swing.JTextArea();
        constituencyResultsTextArea = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Munster Elections 2003");

        constituencyComboBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                constituencyComboBoxActionPerformed(evt);
            }
        });

        partyResultsTextArea.setColumns(20);
        partyResultsTextArea.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        partyResultsTextArea.setRows(5);

        constituencyResultsTextArea.setColumns(20);
        constituencyResultsTextArea.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        constituencyResultsTextArea.setRows(5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(constituencyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partyResultsTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(constituencyResultsTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(constituencyResultsTextArea)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(constituencyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(partyResultsTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 146, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void constituencyComboBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_constituencyComboBoxActionPerformed
    {//GEN-HEADEREND:event_constituencyComboBoxActionPerformed
		constituencyComboBoxActionPerformed();
    }//GEN-LAST:event_constituencyComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> constituencyComboBox;
    private javax.swing.JTextArea constituencyResultsTextArea;
    private javax.swing.JTextArea partyResultsTextArea;
    // End of variables declaration//GEN-END:variables

}
